package Clases;

public class nombreMonedas {
	String monedas = "{\r\n"
			+ "    \"US\": \"Dólar\",\r\n"
			+ "    \"JP\": \"Yen Japonés\",\r\n"
			+ "    \"NL\": \"Euro\",\r\n"
			+ "    \"DE\": \"Euro\",\r\n"
			+ "    \"AU\": \"Dólar australiano\",\r\n"
			+ "    \"AT\": \"Euro\",\r\n"
			+ "    \"BE\": \"Euro\",\r\n"
			+ "    \"BR\": \"Real brasileño\",\r\n"
			+ "    \"BG\": \"Lev búlgaro\",\r\n"
			+ "    \"KH\": \"Riel camboyano\",\r\n"
			+ "    \"CA\": \"Dólar canadiense\",\r\n"
			+ "    \"CZ\": \"Corona checa\",\r\n"
			+ "    \"CY\": \"Euro\",\r\n"
			+ "    \"KR\": \"Won sur-coreano\",\r\n"
			+ "    \"CR\": \"Colón costarricense\",\r\n"
			+ "    \"HR\": \"Euro\",\r\n"
			+ "    \"DK\": \"Corona danesa\",\r\n"
			+ "    \"EG\": \"Libra egipcia\",\r\n"
			+ "    \"AE\": \"Dirham de los Emiratos Árabes Unidos\",\r\n"
			+ "    \"SK\": \"Euro\",\r\n"
			+ "    \"SI\": \"Euro\",\r\n"
			+ "    \"EE\": \"Peso filipino\",\r\n"
			+ "    \"PH\": \"Euro\",\r\n"
			+ "    \"FI\": \"Euro\",\r\n"
			+ "    \"FR\": \"Lari georgiano\",\r\n"
			+ "    \"GR\": \"Euro\",\r\n"
			+ "    \"CN\": \"Yuan chino\",\r\n"
			+ "    \"HU\": \"Forinto húngaro\",\r\n"
			+ "    \"IN\": \"Rupia india\",\r\n"
			+ "    \"IE\": \"Euro\",\r\n"
			+ "    \"IS\": \"Corona islandes\",\r\n"
			+ "    \"IL\": \"Nuevo shéquel\",\r\n"
			+ "    \"IT\": \"Euro\",\r\n"
			+ "    \"LV\": \"Euro\",\r\n"
			+ "    \"LT\": \"Euro\",\r\n"
			+ "    \"LU\": \"Euro\",\r\n"
			+ "    \"MK\": \"Denar macedonio\",\r\n"
			+ "    \"MY\": \"Ringgit malayo\",\r\n"
			+ "    \"MT\": \"Euro\",\r\n"
			+ "    \"MD\": \"Leu moldavo\",\r\n"
			+ "    \"MM\": \"Kyat birmano\",\r\n"
			+ "    \"NG\": \"Naira\",\r\n"
			+ "    \"NO\": \"Corona noruega\",\r\n"
			+ "    \"NZ\": \"Dólar neozelandés\",\r\n"
			+ "    \"PL\": \"Zloty\",\r\n"
			+ "    \"PT\": \"Euro\",\r\n"
			+ "    \"GB\": \"Libra británica\",\r\n"
			+ "    \"RO\": \"Leu rumano\",\r\n"
			+ "    \"RU\": \"Rublo ruso\",\r\n"
			+ "    \"RS\": \"Dinar serbio\",\r\n"
			+ "    \"SG\": \"Dólar de Singapur\",\r\n"
			+ "    \"ZA\": \"Rand sudafricano\",\r\n"
			+ "    \"SE\": \"Corona sueca\",\r\n"
			+ "    \"CH\": \"Franco suizo\",\r\n"
			+ "    \"TH\": \"Baht tailandés\",\r\n"
			+ "    \"TW\": \"Nuevo dólar taiwanés\",\r\n"
			+ "    \"TR\": \"Lira turca\",\r\n"
			+ "    \"UA\": \"Grivna\",\r\n"
			+ "    \"VN\": \"Dong vietnamita\",\r\n"
			+ "    \"AR\": \"Peso\", \r\n"
			+ "    \"BO\": \"Boliviano\", \r\n"
			+ "    \"CL\": \"Peso chileno\", \r\n"
			+ "    \"CO\": \"Peso colombiano\",  \r\n"
			+ "    \"CU\": \"Peso cubano\", \r\n"
			+ "    \"EC\": \"Dólar\", \r\n"
			+ "    \"SV\": \"Dólar\", \r\n"
			+ "    \"ES\": \"Euro\", \r\n"
			+ "    \"GT\": \"Quetzal guatemalteco\", \r\n"
			+ "    \"CQ\": \"Franco CFA de África Central\", \r\n"
			+ "    \"HN\": \"Lempira hondureño\", \r\n"
			+ "    \"MX\": \"Peso mexicano\", \r\n"
			+ "    \"NI\": \"Córdoba nicaragüense\", \r\n"
			+ "    \"PA\": \"Balboa panameño\", \r\n"
			+ "    \"UY\": \"Peso uruguayo\", \r\n"
			+ "    \"PE\": \"Nuevo sol\", \r\n"
			+ "    \"PR\": \"Dólar\", \r\n"
			+ "    \"DO\": \"Peso dominicano\", \r\n"
			+ "    \"VE\": \"Bolívar fuerte\"\r\n"
			+ "}";
}
